"""Add connection_id in variable

Revision ID: c61efb050eba
Revises: 
Create Date: 2025-11-05 09:35:34.002270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61efb050eba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'connection', ['id'])
    # op.create_unique_constraint(None, 'template_connection', ['id'])
    # op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # Step 1: Add the column as nullable
    op.add_column('variable', sa.Column('connection_id', sa.Integer(), nullable=True))
    # Step 2: Create the foreign key (still nullable)
    op.create_foreign_key(op.f('variable_connection_id_fkey'), 'variable', 'connection', ['connection_id'], ['id'])
    op.create_index(op.f('ix_variable_connection_id'), 'variable', ['connection_id'], unique=False)
    # Step 3: Update existing records with a default connection_id
    # Check if connection table has data, if not insert a default
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM connection LIMIT 1) THEN
                INSERT INTO connection (name, created_at) 
                VALUES ('Default Connection', NOW())
                RETURNING id;
            END IF;
        END $$;
    """)
    
    # Now update variables with the first connection
    op.execute("""
        UPDATE variable 
        SET connection_id = (SELECT id FROM connection ORDER BY id LIMIT 1)
        WHERE connection_id IS NULL
    """)
    # Step 4: Now make the column non-nullable
    op.alter_column('variable', 'connection_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('variable_connection_id_fkey', 'variable', type_='foreignkey')
    op.drop_index(op.f('ix_variable_connection_id'), table_name='variable')
    op.drop_column('variable', 'connection_id')
    # op.drop_constraint(None, 'token_blacklist', type_='unique')
    # op.drop_constraint(None, 'template_connection', type_='unique')
    # op.drop_constraint(None, 'connection', type_='unique')
    # ### end Alembic commands ###
