"""set timestamp to updated_at in template model

Revision ID: 8d14c63c7450
Revises: 5421e82fa3b5
Create Date: 2025-11-13 02:38:04.005733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d14c63c7450'
down_revision: Union[str, None] = '5421e82fa3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'connection', ['id'])
    op.alter_column('template', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=False)
    # op.create_unique_constraint(None, 'template_connection', ['id'])
    # op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'token_blacklist', type_='unique')
    # op.drop_constraint(None, 'template_connection', type_='unique')
    op.alter_column('template', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=True)
    # op.drop_constraint(None, 'connection', type_='unique')
    # ### end Alembic commands ###
