"""use template_connection instead of connection in variable

Revision ID: 5421e82fa3b5
Revises: c61efb050eba
Create Date: 2025-11-11 08:24:10.080111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5421e82fa3b5'
down_revision: Union[str, None] = 'c61efb050eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'connection', ['id'])
    # op.create_unique_constraint(None, 'template_connection', ['id'])
    # op.create_unique_constraint(None, 'token_blacklist', ['id'])
    op.drop_constraint(op.f('variable_connection_id_fkey'), 'variable', type_='foreignkey')
    op.create_foreign_key(op.f('variable_connection_id_fkey'), 'variable', 'template_connection', ['connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('variable_connection_id_fkey'), 'variable', type_='foreignkey')
    op.create_foreign_key(op.f('variable_connection_id_fkey'), 'variable', 'connection', ['connection_id'], ['id'])
    # op.drop_constraint(None, 'token_blacklist', type_='unique')
    # op.drop_constraint(None, 'template_connection', type_='unique')
    # op.drop_constraint(None, 'connection', type_='unique')
    # ### end Alembic commands ###
