"""change brand_id to plc_brand_id in plc_type

Revision ID: 2f3d330a1e36
Revises: f4ca3a46b6c9
Create Date: 2025-08-13 11:31:06.169740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f3d330a1e36'
down_revision: Union[str, None] = 'f4ca3a46b6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('plc_type', sa.Column('plc_brand_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_plc_type_brand_id'), table_name='plc_type')
    op.create_index(op.f('ix_plc_type_plc_brand_id'), 'plc_type', ['plc_brand_id'], unique=False)
    op.drop_constraint(op.f('plc_type_brand_id_fkey'), 'plc_type', type_='foreignkey')
    op.create_foreign_key(None, 'plc_type', 'plc_brand', ['plc_brand_id'], ['id'])
    op.drop_column('plc_type', 'brand_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plc_type', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'plc_type', type_='foreignkey')
    op.create_foreign_key(op.f('plc_type_brand_id_fkey'), 'plc_type', 'plc_brand', ['brand_id'], ['id'])
    op.drop_index(op.f('ix_plc_type_plc_brand_id'), table_name='plc_type')
    op.create_index(op.f('ix_plc_type_brand_id'), 'plc_type', ['brand_id'], unique=False)
    op.drop_column('plc_type', 'plc_brand_id')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
